CREATE TABLE claims (
CliamID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
customerID INT,
OrderId INT,
image VARCHAR(50),
dttm DATETIME DEFAULT CURRENT_TIMESTAMP,
status VARCHAR(30),
details VARCHAR(100)
);