CREATE TABLE products  (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	type_id VARCHAR(10) NOT NULL,
	name VARCHAR(50) NOT NULL,
	image VARCHAR(250),
	status_id VARCHAR(10) NOT NULL,
	price VARCHAR(10) NOT NULL,
	stock VARCHAR(5) NOT NULL,
    weight_id VARCHAR(5) NOT NULL
);